config/urls.py
from django.contrib import admin
from django.urls import path, include
#mediaのルート追加
from django.contrib.staticfiles.urls import static
from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('hamburger.urls')),
    path('accounts/',include('allauth.urls')),
]

#開発サーバーでメディア配信をできるようにする設定
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hamburger/urls.py
from django.urls import path
from . import views

app_name='hamburger'
urlpatterns = [
    path('',views.IndexView.as_view(),name="index"),
    
    #Mac
    path('Mac-create/',views.MacCreateView.as_view(), name = "Mac_create"),
    path('Mac-update/<int:pk>/',views.MacUpdateView.as_view(),name = "Mac_update"),
    path('Mac-delete/<int:pk>/',views.MacDeleteView.as_view(),name = "Mac_delete"),
    #Mos
    path('Mos-create/',views.MosCreateView.as_view(), name = "Mos_create"),
    path('Mos-update/<int:pk>/',views.MosUpdateView.as_view(),name = "Mos_update"),
    path('Mos-delete/<int:pk>/',views.MosDeleteView.as_view(),name = "Mos_delete"),
    #BurgerKing
    path('BurgerKing-create/',views.BurgerKingCreateView.as_view(), name = "BurgerKing_create"),
    path('BurgerKing-update/<int:pk>/',views.BurgerKingUpdateView.as_view(),name = "BurgerKing_update"),
    path('BurgerKing-delete/<int:pk>/',views.BurgerKingDeleteView.as_view(),name = "BurgerKing_delete"),

    path('mac_list/', views.MacListView.as_view(), name='mac_list'),
    path('mos_list/', views.MosListView.as_view(), name='mos_list'),
    path('burgerking_list/', views.BurgerKingListView.as_view(), name='burgerKing_list'),
    path('mac_detail/<int:pk>/', views.MacDetailView.as_view(), name='mac_detail'),
    path('mos_detail/<int:pk>/', views.MosDetailView.as_view(), name='mos_detail'),
    path('burgerking_detail/<int:pk>/', views.BurgerKingDetailView.as_view(), name='burgerking_detail'),

    # お気に入り機能のurl
    path('mac_for_post/', views.mac_for_post, name='mac_for_post'), 

]

hamburger/models.py
from tabnanny import verbose
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

# Create your models here.

class CustomUser(AbstractUser):

    class Meta:
        verbose_name_plural = 'CustomUser'

class Mac(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='id', on_delete=models.PROTECT)
    name = models.CharField(verbose_name='メニュー名', max_length=50)
    price = models.IntegerField(verbose_name='値段', blank=True, null=True)
    ditail = models.TextField(verbose_name='詳細', blank=True, null=True)
    photo = models.ImageField(verbose_name='写真', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Mac'

    def __str__(self):
        return self.name

class Mos(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='id', on_delete=models.PROTECT)
    name = models.CharField(verbose_name='メニュー名', max_length=50)
    price = models.IntegerField(verbose_name='値段', blank=True, null=True)
    ditail = models.TextField(verbose_name='詳細', blank=True, null=True)
    photo = models.ImageField(verbose_name='写真', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Mos'

    def __str__(self):
        return self.name

class BurgerKing(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='id', on_delete=models.PROTECT)
    name = models.CharField(verbose_name='メニュー名', max_length=50)
    price = models.IntegerField(verbose_name='値段', blank=True, null=True)
    ditail = models.TextField(verbose_name='詳細', blank=True, null=True)
    photo = models.ImageField(verbose_name='写真', blank=True, null=True)

    class Meta:
        verbose_name_plural = 'BurgerKing'

    def __str__(self):
        return self.name


class FavoriteMac(models.Model):
    mac = models.ForeignKey(Mac, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name_plural = 'FavoriteMac'

hamburger/forms.py
from django import forms

#Mac
from .models import Mac

class MacCreateForm(forms.ModelForm):
    class Meta:
        model = Mac
        fields = ('name','price','ditail','photo')

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'

#Mos
from .models import Mos

class MosCreateForm(forms.ModelForm):
    class Meta:
        model = Mos
        fields = ('name','price','ditail','photo')

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'


#BurgerKing
from .models import BurgerKing

class BurgerKingCreateForm(forms.ModelForm):
    class Meta:
        model = BurgerKing
        fields = ('name','price','ditail','photo')

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            for field in self.fields.values():
                field.widget.attrs['class'] = 'form-control'

hamburger/views.py
from tokenize import Hexnumber
from django.shortcuts import render
from django.views import generic
from .models import Mac, Mos, BurgerKing, FavoriteMac
from django.http import JsonResponse  
from django.shortcuts import get_object_or_404  

import logging

from django.urls import reverse_lazy
from django.contrib import messages

#作成
from .forms import MacCreateForm
from .forms import MosCreateForm
from .forms import BurgerKingCreateForm

#表示
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Mac
from .models import Mos
from .models import BurgerKing

# Create your views here.
class IndexView(generic.TemplateView):
    template_name="index.html"

#mac
class MacCreateView(LoginRequiredMixin,generic.CreateView):
    model = Mac
    template_name = 'Mac_create.html'
    form_class = MacCreateForm
    success_url = reverse_lazy('hamburger:mac_list')

    def form_valid(self, form):
        hamburger = form.save(commit=False)
        hamburger.user = self.request.user
        hamburger.save()
        messages.success(self.request,'データを作成しました。')
        return super().form_valid(form)

    def form_invalid(self,form):
        messages.error(self.request,"データの作成に失敗しました。")
        return super().form_invalid(form)

class MacUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = Mac
    template_name = 'Mac_update.html'
    form_class = MacCreateForm

    def get_success_url(self):
        return reverse_lazy('hamburger:mac_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'データを更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "データの更新に失敗しました。")
        return super().form_invalid(form)

class MacDeleteView(LoginRequiredMixin,generic.DeleteView):
    model = Mac
    template_name = 'Mac_delete.html'
    success_url = reverse_lazy('hamburger:mac_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "データを削除しました。")
        return super().delete(request, *args, **kwargs)





#Mos
class MosCreateView(LoginRequiredMixin,generic.CreateView):
    model = Mos
    template_name = 'Mos_create.html'
    form_class = MosCreateForm
    success_url = reverse_lazy('hamburger:mos_list')

    def form_valid(self, form):
        hamburger = form.save(commit=False)
        hamburger.user = self.request.user
        hamburger.save()
        messages.success(self.request,'データを作成しました。')
        return super().form_valid(form)

    def form_invalid(self,form):
        messages.error(self.request,"データの作成に失敗しました。")
        return super().form_invalid(form)

class MosUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = Mos
    template_name = 'Mos_update.html'
    form_class = MosCreateForm

    def get_success_url(self):
        return reverse_lazy('hamburger:mos_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'データを更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "データの更新に失敗しました。")
        return super().form_invalid(form)

class MosDeleteView(LoginRequiredMixin,generic.DeleteView):
    model = Mos
    template_name = 'Mos_delete.html'
    success_url = reverse_lazy('hamburger:mos_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "データを削除しました。")
        return super().delete(request, *args, **kwargs)





#BurgerKing
class BurgerKingCreateView(LoginRequiredMixin,generic.CreateView):
    model = BurgerKing
    template_name = 'BurgerKing_create.html'
    form_class = BurgerKingCreateForm
    success_url = reverse_lazy('hamburger:burgerking_list')

    def form_valid(self, form):
        hamburger = form.save(commit=False)
        hamburger.user = self.request.user
        hamburger.save()
        messages.success(self.request,'データを作成しました。')
        return super().form_valid(form)

    def form_invalid(self,form):
        messages.error(self.request,"データの作成に失敗しました。")
        return super().form_invalid(form)

class BurgerKingUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = BurgerKing
    template_name = 'BurgerKing_update.html'
    form_class = BurgerKingCreateForm

    def get_success_url(self):
        return reverse_lazy('hamburger:burgerking_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'データを更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "データの更新に失敗しました。")
        return super().form_invalid(form)

class BurgerKingDeleteView(LoginRequiredMixin,generic.DeleteView):
    model = BurgerKing
    template_name = 'BurgerKing_delete.html'
    success_url = reverse_lazy('hamburger:burgerKing_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "データを削除しました。")
        return super().delete(request, *args, **kwargs)


class MacListView(generic.ListView):
    model = Mac
    template_name = 'mac_list.html'
    paginate_by = 8

    def get_queryset(self):
        macs = Mac.objects.order_by('price')
        return macs

class MosListView(generic.ListView):
    model = Mos
    template_name = 'Mos_list.html'
    paginate_by = 8

    def get_queryset(self):
        macs = Mos.objects.order_by('price')
        return macs

class BurgerKingListView(generic.ListView):
    model = BurgerKing
    template_name = 'burgerKing_list.html'
    paginate_by = 8

    def get_queryset(self):
        macs = BurgerKing.objects.order_by('price')
        return macs

class MacDetailView(generic.DetailView):
    model = Mac
    template_name = 'mac_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        like_for_post_count = self.object.favoritemac_set.count()
        # ポストに対するイイね数
        context['like_for_post_count'] = like_for_post_count
        # ログイン中のユーザーがイイねしているかどうか
        if self.object.favoritemac_set.filter(user=self.request.user).exists():
            context['is_user_liked_for_post'] = True
        else:
            context['is_user_liked_for_post'] = False

        return context

class MosDetailView(generic.DetailView):
    model = Mos
    template_name = 'mos_detail.html'

class BurgerKingDetailView(generic.DetailView):
    model = BurgerKing
    template_name = 'burgerking_detail.html'

def mac_for_post(request):
    post_pk = request.POST.get('post_pk')
    context = {
        'user': f'{request.user.last_name} {request.user.first_name}',
    }
    post = get_object_or_404(Mac, pk=post_pk)
    like = FavoriteMac.objects.filter(mac=post, user=request.user)

    if like.exists():
        like.delete()
        context['method'] = 'delete'
    else:
        like.create(mac=post, user=request.user)
        context['method'] = 'create'

    context['like_for_post_count'] = post.favoritemac_set.count()

    return JsonResponse(context)

hamburger/templates/BurgerKing_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}作成{% endblock %}

{% block active_BurgerKing_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">作成</button>
        </form>
    </div>
</div>
{% endblock %}

hamburger/templates/BurgerKing_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}削除{% endblock %}

{% block active_BurgerKing_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST">
            {% csrf_token %}
            <p>本当に削除しますか？</p>
            <button class="btn btn-primary mt-5" type="submit">削除</button>
            <a class="btn btn-secondary mt-5 ml-2" href="{% url 'hamburger:burgerking_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

hamburger/templates/BurgerKing_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}編集{% endblock %}

{% block active_BurgerKing_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">更新</button>
            <a class="btn btn-secondary ml-2" href="{% url 'hamburger:burgerking_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

hamburger/templates/Mac_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}作成{% endblock %}

{% block active_Mac_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">作成</button>
        </form>
    </div>
</div>
{% endblock %}

hamburger/templates/Mac_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}削除{% endblock %}

{% block active_Mac_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST">
            {% csrf_token %}
            <p>本当に削除しますか？</p>
            <button class="btn btn-primary mt-5" type="submit">削除</button>
            <a class="btn btn-secondary mt-5 ml-2" href="{% url 'hamburger:mac_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

hamburger/templates/Mac_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}編集{% endblock %}

{% block active_Mac_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">更新</button>

            <a class="btn btn-secondary ml-2" href="{% url 'hamburger:mac_detail' object.pk %}">キャンセル</a>

        </form>
    </div>
</div>
{% endblock %}

hamburger/templates/Mos_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}作成{% endblock %}

{% block active_Mos_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">作成</button>
        </form>
    </div>
</div>
{% endblock %}

hamburger/templates/Mos_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}編集{% endblock %}

{% block active_Mos_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <form method="POST" enctype='multipart/form-data'>
            {% csrf_token %}
            <table class="table">
                {{ form.as_table }}
            </table>
            <button class="btn btn-primary" type="submit">更新</button>
            <a class="btn btn-secondary ml-2" href="{% url 'hamburger:mos_detail' object.pk %}">キャンセル</a>
        </form>
    </div>
</div>
{% endblock %}

hamburger/templates/burgerKing_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}商品一覧｜Shop Menu{% endblock %}

{% block contents %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">バーガーキング</h1>
            <p class="lead fw-normal text-white-50 mb-0">バーガーキングの商品一覧</p>
            {% if user.is_authenticated %}
                <a class="btn btn-success mt-5 mb-3" href="{% url 'hamburger:BurgerKing_create' %}">メニューを追加</a>
            {% endif %}
        </div>
    </div>
</header>
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for burgerKing in burgerking_list %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    {% if burgerKing.photo %}
                    <img class="card-img-top" src="{{ burgerKing.photo.url }}" alt="..." />
                    {% endif %}
                    <!-- Product details-->
                    
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ burgerKing.name }}</h5>
                            <!-- Product price-->
                            {{ burgerKing.price }}円
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'hamburger:burgerking_detail' burgerKing.pk%}">詳細</a></div>
                    </div>
                    
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- ページネーション処理 -->
        {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}

            <!-- ページ数表示 -->
            {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% endif %}
            {% endfor %}
            <!-- 次のページリンク -->
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
</section>
{% endblock %}

hamburger/templates/mac_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}商品一覧｜Shop Menu{% endblock %}

{% block extrahead %}
<!-- Font Awesome -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
<!-- MDB -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.10.1/mdb.min.css" rel="stylesheet" />
{% endblock %}
{% block contents %}

<section>
  <div class="container px-5">
      <div class="row gx-5 align-items-center">
          <div class="col-lg-6">
              <div class="p-5"><img class="img-fluid" src="{{ object.photo.url }}" alt="..." /></div>
          </div>
          <div class="col-lg-6">
              <div class="p-5">
                  <h3 class="display-4">{{ object.name }}</h3>
                  <br>
                  <h4 class="display-5">{{ object.price }}円</h4>
              </div>
          </div>
            <h2 class="border-bottom border-4 border-dark">詳細</h2>
            <h3>{{ object.ditail }}</h3>

          
      </div>
      {% if user.is_authenticated %}
            <a class="btn btn-success mt-5 mb-3" href="{% url 'hamburger:Mac_update' object.pk %}">編集</a>
            <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'hamburger:Mac_delete' object.pk %}">削除</a>
            <div class="card-header">
                {% if is_user_liked_for_post %}
                <button type="button" id="ajax-like-for-post" style="border:none;background:none">
                  <!-- すでにイイねしている時はfasクラス -->
                  <i class="fas fa-heart text-danger" id="like-for-post-icon"></i>
                </button>
                {% else %}
                <button type="button" id="ajax-like-for-post" style="border:none;background:none">
                  <!-- イイねしていないときはfarクラス -->
                  <i class="far fa-heart text-danger" id="like-for-post-icon"></i>
                </button>
                {% endif %}
                <!-- イイねの数 -->
                <span id="like-for-post-count">{{ like_for_post_count }}</span>
                <span>件のイイね</span>
              </div>
      {% endif %}
  </div>
</section>

{% endblock %}

{% block extrajs %}
<script type="text/javascript">
  /* ポストに対するイイね */
  document.getElementById('ajax-like-for-post').addEventListener('click', e => {
    e.preventDefault();
    const url = '{% url "hamburger:mac_for_post" %}';
    fetch(url, {
      method: 'POST',
      body: `post_pk={{post.pk}}`,
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
        'X-CSRFToken': '{{ csrf_token }}',
      },
    }).then(response => {
      return response.json();
    }).then(response => {
       // イイね数を書き換える
      const counter = document.getElementById('like-for-post-count')
      counter.textContent = response.like_for_post_count
      const icon = document.getElementById('like-for-post-icon')
      // 作成した場合はハートを塗る
      if (response.method == 'create') {
        icon.classList.remove('far')
        icon.classList.add('fas')
        icon.id = 'like-for-post-icon'
      } else {
        icon.classList.remove('fas')
        icon.classList.add('far')
        icon.id = 'like-for-post-icon'
      }
    }).catch(error => {
      console.log(error);
    });
  });
</script>


{% endblock %}

hamburger/templates/mos_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}商品一覧｜Shop Menu{% endblock %}


{% block contents %}

<section>
  <div class="container px-5">
      <div class="row gx-5 align-items-center">
          <div class="col-lg-6">
              <div class="p-5"><img class="img-fluid" src="{{ object.photo.url }}" alt="..." /></div>
          </div>
          <div class="col-lg-6">
              <div class="p-5">
                  <h3 class="display-4">{{ object.name }}</h3>
                  <br>
                  <h4 class="display-5">{{ object.price }}円</h4>
              </div>
          </div>
            <h2 class="border-bottom border-4 border-dark">詳細</h2>
            <h3>{{ object.ditail }}</h3>

          
      </div>
      {% if user.is_authenticated %}
            <a class="btn btn-success mt-5 mb-3" href="{% url 'hamburger:Mos_update' object.pk %}">編集</a>
            <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'hamburger:Mos_delete' object.pk %}">削除</a>
      {% endif %}
  </div>
</section>

{% endblock %}

hamburger/templates/mos_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}商品一覧｜Shop Menu{% endblock %}

{% block contents %}
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">モスバーガー</h1>
            <p class="lead fw-normal text-white-50 mb-0">モスバーガーの商品一覧</p>
            {% if user.is_authenticated %}
                <a class="btn btn-success mt-5 mb-3" href="{% url 'hamburger:Mos_create' %}">メニューを追加</a>
            {% endif %}
        </div>
    </div>
</header>
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for mos in mos_list %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    {% if mos.photo %}
                    <img class="card-img-top" src="{{ mos.photo.url }}" alt="..." />
                    {% endif %}
                    <!-- Product details-->
                    
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{ mos.name }}</h5>
                            <!-- Product price-->
                            {{ mos.price }}円
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'hamburger:mos_detail' mos.pk%}">詳細</a></div>
                    </div>
                    
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- ページネーション処理 -->
        {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            {% endif %}

            <!-- ページ数表示 -->
            {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% endif %}
            {% endfor %}
            <!-- 次のページリンク -->
            {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            {% endif %}
        </ul>
        {% endif %}
    </div>
</section>
{% endblock %}